### ISSUE TITLE
Area documentation

### ISSUE THREAD

**Issue by pnorman** [e-n-f/datamaps#11]
The docs state

> -p area
> Specifies a multiplier for dot sizes. Point brightness is automatically reduced by the same factor so the total brightness remains constant, just diffused. The default is 1.
> -p garea
> Specifies a Gaussian brush instead of a flat disk, as well as a multiplier for dot sizes.

Because both are -p, it's not particularly clear how to specify a Gaussian brush.

**Comment by e-n-f** [comment]
Thanks for the report. I'll add an example.

**Comment by e-n-f** [comment]
Hopefully clearer after https://github.com/ericfischer/datamaps/commit/9648571e559a365e646a480e4d527f11a2fca2e2
