### ISSUE TITLE
merging input data to index

### ISSUE THREAD

**Issue by marcioaguiar** [e-n-f/datamaps#12]
It's not clear in the documentation if the encode tool will merge data to the index if a call it pointing to an existing index. Is that the case?

I tried to read the source code, but I guess my C skills are a little bit rusty.

Thanks for the great project.

**Comment by e-n-f** [comment]
Sorry about the mystery! Encode will only write into a new file, but you can use Merge to combine two files into one, so the way to add data is to encode a new file and then merge it with the old one. I'll add documentation for that.

**Comment by e-n-f** [comment]
Documented in 93a78b7

**Comment by marcioaguiar** [comment]
Great! Thanks!
