### ISSUE TITLE
Tile count estimate

### ISSUE THREAD

**Issue by umaar** [e-n-f/datamaps#18]
I was generating a tileset for a single zoom level (15) and actually ran out of [inodes](https://en.wikipedia.org/wiki/Inode)!

Command: `enumerate -z15 -Z15 dirname | xargs -L1 -P8 ./render -o tiles/dirname`

To ensure the machine I'm using is suitable, how can I figure out the total file count (not size) for zoom level 15?

**Comment by e-n-f** [comment]
You can do `enumerate -z15 -Z15 dirname | wc -l` to count the tiles in advance.

**Comment by e-n-f** [comment]
This is one of the problems that has led me to write https://github.com/mapbox/tippecanoe as a replacement. Using vector tiles, and writing those tiles to an mbtiles container rather than to individual files, avoids the massive number of tile files at high zoom levels.

**Comment by umaar** [comment]
Heh, so quick and to the point! Thanks, that's exactly what I needed.

I ran the command, for everything up to zoom level 15, it's around 14 million files! I think I will check out your tippecanoe project. Just wondering, with your datamaps project, I'd do something like:

```
# Encode location data
cat file | ./encode -o directoryname -z 16

# Produce a one-off static map
./render -A -- directoryname zoom minlat minlon maxlat maxlon > foo.png

# Produce a tileset for a detailed + interactive map
enumerate -z14 dirname | xargs -L1 -P8 ./render -o tiles/dirname
```

For each of those commands (`encode`, `render` & `enumerate`), are there corresponding equivalents in tippecanoe? I'll have to read more on the documentation and more about mbtiles, but not having to create so many files sounds great.

All the work you do is fascinating and inspiring, thanks!
