### ISSUE TITLE
Error on Mavericks

### ISSUE THREAD

**Issue by aaronlidman** [e-n-f/datamaps#2]
When compiling `render`:

> undef: ___sincos_stret
> Undefined symbols for architecture x86_64:

The solution was to run `xcode-select --install` which I found here: https://github.com/mxcl/homebrew/issues/22553

I'm only using the xcode CLI tools, maybe that's it?

**Comment by e-n-f** [comment]
I should have replied to this long ago. I'm using the full XCode installation and haven't run into it, but I don't think I'm doing anything too strange with math library calls. I wonder if it's broken for anyone else.

**Comment by springmeyer** [comment]
I'd recommend closing this and mark it up to a bug in the apple command line tools.

**Comment by e-n-f** [comment]
Fair enough!
