### ISSUE TITLE
License and version

### ISSUE THREAD

**Issue by deanwilson** [e-n-f/datamaps#3]
Hi Eric
  We've written a specfile for datamaps to aid in our deployment on Centos and Fedora based machines and it'd be handy if we could assign values for license and version number to it. We'd be happy to submit the specfile for inclusion via a PR too.

Thank you for your time.

**Comment by e-n-f** [comment]
@deanwilson Yes, please send a pull request with the specfile and anything else you'd like added to the repository. I'll add a license file too.

**Comment by e-n-f** [comment]
@deanwilson Added a 2-clause BSD license (https://github.com/ericfischer/datamaps/blob/master/LICENSE.md)
