### ISSUE TITLE
Enumerate a single zoom level?

### ISSUE THREAD

**Issue by aaronlidman** [e-n-f/datamaps#9]
Any way of enumerating over just a single zoom level? I'm just doing slight brightness and base changes on each zoom level manually to get more control than ramp allows.

Right now I'm just enumerating through everything up to a zoom level and then throwing away everything I don't need, which is wasteful and slow.

**Comment by e-n-f** [comment]
Oh, sorry, yes @aaronlidman, you can enumerate a single zoom by specifying both -z and -Z for maximum and minimum. So if you want just z12, <code>enumerate -z12 -Z12</code>.

**Comment by aaronlidman** [comment]
Great, thanks Eric. Realized it's pretty clear in the code too, sorry about that.

**Comment by e-n-f** [comment]
Sorry about the poor documentation! Will merge your pull request as soon as
I am back at a computer.
